# Generated by Django 4.1.1 on 2024-12-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_directorgeneral_especialidad_laboratorio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
